### ISSUE TITLE
OpenCV Error: Parsing error

### ISSUE THREAD

**Issue by r1089** [luca-m/emotime#37]
hi ,i am trying to run your project .for some time it was working fine but after a few trys it is giving some errors like this and i request you to help me out.
errors:
 OpenCV Error: Parsing error (../dataset_svm_354_cbcl1_1vsallext/classifiers/svm/(0): Valid XML should start with '<?xml ...?>') in icvXMLParse, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/persistence.cpp, line 2252
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/persistence.cpp:2252: error: (-212) ../dataset_svm_354_cbcl1_1vsallext/classifiers/svm/(0): Valid XML should start with '<?xml ...?>' in function icvXMLParse

Aborted

**Comment by dbellavista** [comment]
Can you please report the command and the parameters you used?

**Comment by r1089** [comment]
thanks...I got the error...
 i am developing a similar kind of project for my academics.so i need your help and guidance for building and understanding your project.so please help me out..

**Comment by Hera1013** [comment]
I got same issue.. 
OpenCV Error: Parsing error (../svm_1vsall_1_5_8_95c2eb0b58/classifiers(0): Valid XML should start with '<?xml ...?>') in icvXMLParse, file /Users/Yang/Documents/opencv/modules/core/src/persistence.cpp, line 2252
libc++abi.dylib: terminating with uncaught exception of type cv::Exception: /Users/Yang/Documents/opencv/modules/core/src/persistence.cpp:2252: error: (-212) ../svm_1vsall_1_5_8_95c2eb0b58/classifiers(0): Valid XML should start with '<?xml ...?>' in function icvXMLParse

Did you fix that?

**Comment by luca-m** [comment]
Is the file path correct? I mean, opened is saying the classifier is not an
xml file ..

Sent form my phone.
Il 09/mag/2016 17:36, "Hera1013" <notifications@github.com> ha scritto:

**Comment by Hera1013** [comment]
Thank you so much for your replying!!


The path is correct, and I opened all xml files and they all start with <?xml ...?>.


Maybe because the Trained models 1vsall<https://copy.com/As78VEsZD3IFTWIA> and 1vsallext<https://copy.com/UbTJW8MKXSsCLch8> links in your Github are no longer available for downloading, so I used old version? Would you mind updating the links?


looking forward to your reply.


Best,

Yang

________________________________
发件人: lucam <notifications@github.com>
发送时间: 2016年5月9日 12:22:25
收件人: luca-m/emotime
抄送: Han, Yang; Comment
主题: Re: [luca-m/emotime] OpenCV Error: Parsing error (#37)

Is the file path correct? I mean, opened is saying the classifier is not an
xml file ..

Sent form my phone.
Il 09/mag/2016 17:36, "Hera1013" <notifications@github.com> ha scritto:

> I got same issue..
> OpenCV Error: Parsing error
> (../svm_1vsall_1_5_8_95c2eb0b58/classifiers(0): Valid XML should start with
> '<?xml ...?>') in icvXMLParse, file
> /Users/Yang/Documents/opencv/modules/core/src/persistence.cpp, line 2252
> libc++abi.dylib: terminating with uncaught exception of type
> cv::Exception:
> /Users/Yang/Documents/opencv/modules/core/src/persistence.cpp:2252: error:
> (-212) ../svm_1vsall_1_5_8_95c2eb0b58/classifiers(0): Valid XML should
> start with '<?xml ...?>' in function icvXMLParse
>
> Did you fix that?
>
> ―
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/luca-m/emotime/issues/37#issuecomment-217900470>
>

―
