### ISSUE TITLE
train_cli problem with openCV

### ISSUE THREAD

**Issue by flecheria** [luca-m/emotime#43]
Until the svm training all seems good, after that I receive this error about openCV, any hints?
![issue](https://cloud.githubusercontent.com/assets/266848/7218763/d4c7800a-e67f-11e4-8b5f-331de6a3111e.jpg)

**Comment by flecheria** [comment]
I can test right now, but could be something inside here?

https://github.com/luca-m/emotime/blob/master/src/training/SVMClassifier.h

How is suppose to work? It seems a problem with OpenCV data type...

**Comment by dbellavista** [comment]
@flecheria to adjust your configuration you have to change in the `[FOLDER]` section the `TRAIN` value into something else, like `trainfiles`

```
[FOLDER]
...
# Folder containing the csv files of the features for training set and validation set (one file per classifier)
TRAIN:      trainfiles
...
```

Then recompile and it should work. (BTW this bug was present into windows and macosx systems, the linux default compiler seemed to perform an automatic cast).
