### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by stelila** [luca-m/emotime#47]
I did the configuration for Windows. I configured the program using Cmake and then generated it for Visual studio 12 2013 Win64. However when I open the solution in visual studio and try to run ALL_BUILD I get Unable to run program 'C:...\ALL_BUILD access is denied. Any help?
![problem](https://cloud.githubusercontent.com/assets/5880994/7480739/8f55859a-f362-11e4-9b63-6c92629d4dd7.png)

**Comment by rkrishnan2012** [comment]
Pretty sure QT works better than visual studio for this stuff. Try to do a
clean and it could also be because of spaces in the path...not sure though.

**Comment by stelila** [comment]
Dear Sir,


How would I go about it if I were to run it with QT?

If you could also describe the process of running the program with Visual Studio in detail to see If I did something wrong, I would be grateful.


Looking forward to your reply, 

Stelios






Sent from Windows Mail





From: Rohit G Krishnan
Sent: ‎Friday‎, ‎15‎ ‎May‎ ‎2015 ‎04‎:‎23
To: luca-m/emotime
Cc: stelila




Pretty sure QT works better than visual studio for this stuff. Try to do a
clean and it could also be because of spaces in the path...not sure though.

**Comment by luca-m** [comment]
We'll wait a brave knight with a windows machine and VisualStudio :+1:

**Comment by anastasiaTesla** [comment]
I'm using Visual Studio 2010 32 bit with OpenCV 2.4.12 and faced the problem you asked !
In MVSC in the solution explorer just select the BUILD ALL project, right click and select Build (first choice in the menu). Your other choice is to set some of the other projects as Basic (right click the project you want and select Set as Startup Project).I do recommend the first option.In the same manner, in order the assets folder to be populated, select the INSTALL project and right click then build.

If the build fails, maybe you have ambiguous call to pow function and maybe you need to include stdint.At least that were my errors.

If you want to run the .exe files, use command line arguments. In MVSC select the project you want to run, make it first basic and then again right click=> properties=>debugging=>command arguments and fill in your arguments. Else you can run it from cmd, but in this case I recommend using Cygwin because you will maybe need to load many classifiers simultaneously and I personally do not know a command  in windows cmd that do it automatically.

**Comment by luca-m** [comment]
Closing.
