### ISSUE TITLE
issue while running the command gui.py 

### ISSUE THREAD

**Issue by r-sreesaran** [luca-m/emotime#56]
python gui.py --cfg  ../resources/haarcascade_eye.xml  --mode svm --eye-correction ../datasets/002/
here datasets/002/ contain all the images for which i need to the view the emotion  

while running the above command i am getting the following issue 

ERR: something wrong (File contains no section headers.
file: ../resources/haarcascade_eye.xml, line: 1
'<?xml version="1.0"?>\n')

Q1 ) is my usage of the command correct ? , if not please do provide some examples

**Comment by anastasiaTesla** [comment]
I think after --cfg you must put the dataset's configuarion path. That is a file in assets folder with extension .cfg (there is a file named example_dataset.cfg, you can customise it and use it).
All these kind of arguments, e.g. resources such as classifiers path or parameters of training, must go in this file.
So that's the reason you are getting this error.
The parser expects to see sections such as [CLASSES], [TRAINING] etc.
The destination folder with the test-images I think it's ok

**Comment by r-sreesaran** [comment]
the problem was solved , thankyou very much .  I facing a new issue 
./emotimegui_cli: error while loading shared libraries: libopencv_objdetect.so.2.4: cannot open shared object file: No such file or directory
