### ISSUE TITLE
About the classifiers given for master-branch

### ISSUE THREAD

**Issue by anastasiaTesla** [luca-m/emotime#59]
Hello,
because I'm intending to use your application about my master thesis, I would like to know about the perfomance of the classifiers given as more appropriate for the master branch.
Here is the link of the classifiers https://www.copy.com/s/t%3Ac4rOYmPgAYrdxdoS%3Bp%3A%252Fsvm_1vsallext_74_74_1_5_8_7bfc0cda.tar.gz%3Boid%3A1094
When I use them both in live webcam sessions and videos of other people, I'm getting always neutral with score 3.5
I have also tried these https://www.copy.com/s/UbTJW8MKXSsCLch8 and they worked better, but never I'm getting a better score than 3 in the detected emotion
Today I recompiled the source code and they insist to give the same results (I thought some changes in code I made was the problem)
I try to validate them using your images in the report folder but they do not give me the written emotions.
Also when I load the classifiers from the 1vsall versions, I'm getting Unkown Emotion with score 1,{something}e-038. Must I make changes in the code when I run the 1vsall classfiers? For example in the SVMEmoDetector class must I change the predict method?

If I'm doing something wrong please let me know!

**Comment by luca-m** [comment]
Hi,
That models are trained with Cohn-kanade face db and the image in the report folder are screenshot recorded in early development stage, and maybe does not properly trigger face detection and models in with the current codebase.
The score you see is the result of a multi-class classifier realized with many svm binary classifiers and the score you read mean that the that "emotion" received 3 votes from the binary classifiers (should be the higher vote). About the Unknown this could happen when the multi-class classifier was not able to determine an higher vote for that class.
Also older models are not compatible with newer codebase due to modification to gabor bank filters and image resize. As personal advice i suggest you to use and train 1vsallext models because they offer better approach to classification (many vs many approach). 
If you have access to other dataset or want play with gabor bank parameters you are welcome. Also if you'd like to add a better cli or gui support you are welcome too :)
